spring.application.name=customer-service

# Conexión a MongoDB Atlas (Reactiva para WebFlux)
spring.data.mongodb.uri=mongodb+srv://arturo:nttdata2026@sesion01.ompkwtp.mongodb.net/customer_db?retryWrites=true&w=majority&appName=Sesion01

# Nombre de la base de datos
spring.data.mongodb.database=customer_db

# Mostrar logs de las consultas (Opcional, pero ayuda mucho a ver qué pasa)
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
